con<-read.csv2("household_power_consumption.txt")
library(dplyr)
data<-tbl_df(con)
rm(con)
data1<-mutate(data,Date=as.character(Date))
data2<-filter(data1,Date=="1/2/2007"|Date=="2/2/2007")
library(lubridate)
t<-paste(data2$Date,as.character(data2$Time),sep=" ")
x<-as.numeric(as.character(data2$Global_active_power))
a<-as.numeric(as.character(data2$Sub_metering_1))
b<-as.numeric(as.character(data2$Sub_metering_2))
c<-as.numeric(as.character(data2$Sub_metering_3))
data3<-mutate(data2,Time=dmy_hms(t),Global_active_power=x,Sub_metering_1=a,Sub_metering_2=b,Sub_metering_3=c)
windows()
par("mfrow"=c(1,2))
with(data3,plot(Time,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
with(data3,lines(Time,Sub_metering_1,col="black"))
with(data3,lines(Time,Sub_metering_2,col="red"))
with(data3,lines(Time,Sub_metering_3,col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()