con<-read.csv2("household_power_consumption.txt")
library(dplyr)
data<-tbl_df(con)
rm(con)
data1<-mutate(data,Date=as.character(Date))
data2<-filter(data1,Date=="1/2/2007"|Date=="2/2/2007")
windows()
par("mfrow"=c(2,2))
x<-as.numeric(as.character(data2$Global_active_power))
library(lubridate)
t<-paste(data2$Date,as.character(data2$Time),sep=" ")
data3<-mutate(data2,Time=dmy_hms(t),Global_active_power=x)
plot(data3$Time,data3$Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)")
data4<-mutate(data3,Voltage=as.numeric(as.character(Voltage)))
plot(data4$Time,data4$Voltage,type="l",xlab="datetime",ylab="Voltage")
a<-as.numeric(as.character(data2$Sub_metering_1))
b<-as.numeric(as.character(data2$Sub_metering_2))
c<-as.numeric(as.character(data2$Sub_metering_3))
data5<-mutate(data4,Sub_metering_1=a,Sub_metering_2=b,Sub_metering_3=c)
with(data5,plot(Time,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
with(data5,lines(Time,Sub_metering_1,col="black"))
with(data5,lines(Time,Sub_metering_2,col="red"))
with(data5,lines(Time,Sub_metering_3,col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
data6<-mutate(data5,Global_reactive_power=as.numeric(as.character(Global_reactive_power)))
plot(data6$Time,data6$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.copy(png,file="plot4.png")
dev.off()