con<-read.csv2("household_power_consumption.txt")
library(dplyr)
data<-tbl_df(con)
rm(con)
data1<-mutate(data,Date=as.character(Date))
data2<-filter(data1,Date=="1/2/2007"|Date=="2/2/2007")
x<-as.numeric(as.character(data2$Global_active_power))
windows()
par("mfrow"=c(1,2))
hist(x,main="Global Active Power",xlab="Global Active Power (kilowatts)", col="red")
dev.copy(png,file="plot1.png")
dev.off()